lr: 0.0001
batch_size: 4
num_epochs: 10

train_paths:
  - "C:\\arissa\\Deepfake detection\\Data\\train" #train set path

val_paths:
  - "C:\\arissa\\Deepfake detection\\Data\\valid" # validation set path

early_stopping_patience: 3  # Stop training if val_loss doesn’t improve after 3 epochs
scheduler_factor: 0.5        # LR drops by half if stuck
scheduler_patience: 2        # Wait 2 epochs before adjusting LR
monitor_metric: val_loss     # Metric to monitor for callbacks

log_every_n_steps: 1         # Show updates each batch
save_top_k: 1                # Only keep the best model
